### ISSUE TITLE
 leadd_example.py:   import pyLEADD # LEADD must be imported after the RDKit!

### ISSUE THREAD

**Issue by sdnyer** [UAMCAntwerpen/LEADD#2]
Trying to run the following command:

            python3.10 leadd_example.py reconstruction_settings.txt . -v

and received the following error:

            <pre>Traceback (most recent call last):
              File &quot;/home/ubuntu/LEADD/example/leadd_example.py&quot;, line 6, in &lt;module&gt;
                import pyLEADD # LEADD must be imported after the RDKit!
            </pre>

echo $PYTHONPATH
             :/lib:/home/ubuntu/anaconda3/envs/LEADD/lib:/lib

Any idea how to resolve this library problem.  Thanks In Advance!!

**Comment by sdnyer** [comment]
Resolved.  This was due to the missing pybind installation prior to make.

pybind11](https://github.com/pybind/pybind11) (>= 2.6.2). If you clone this repository it should be included in the distribution.

**Comment by AlanKerstjens** [comment]
Although this is already solved I'd like to add some context for posterity. `pybind11` is included as a submodule. If you'd like to clone it alongside LEADD you should either use the `--recurse-submodules` flag when cloning the LEADD repository or run `git submodule init && git submodule update` after cloning the repository. This may not have been clear enough so I've update the quoted README section to reflect this.
