### ISSUE TITLE
Build Issue - Boost header file not found

### ISSUE THREAD

**Issue by Tenchberry** [UAMCAntwerpen/LEADD#4]
Hi there,

I'm currently following the compilation instructions for LEADD (On a CentOS 7 machine). Everything is fine on my end until the "make install clean" compilation step, where I get the following error:-

[  2%] Building CXX object CMakeFiles/Graph.dir/source/Graph.cpp.o
[  4%] Linking CXX shared library libGraph.so
[  4%] Built target Graph
[  6%] Building CXX object CMakeFiles/Connection.dir/source/Connection.cpp.o
[  8%] Linking CXX shared library libConnection.so
[  8%] Built target Connection
[ 10%] Building CXX object CMakeFiles/Pseudofragment.dir/source/Pseudofragment.cpp.o
In file included from /bfhome/kabdelmaksoud/software/miniconda3/envs/LEADD/include/rdkit/DataStructs/SparseIntVect.h:19,
                 from /bfhome/kabdelmaksoud/software/miniconda3/envs/LEADD/include/rdkit/GraphMol/Fingerprints/MorganFingerprints.h:45,
                 from /bfprojects/Development/Scripts/kabdelmaksoud/LEADD/source/Pseudofragment.hpp:11,
                 from /bfprojects/Development/Scripts/kabdelmaksoud/LEADD/source/Pseudofragment.cpp:1:
/bfhome/kabdelmaksoud/software/miniconda3/envs/LEADD/include/rdkit/RDGeneral/StreamOps.h:21:10: fatal error: boost/detail/endian.hpp: No such file or directory
   21 | #include <boost/detail/endian.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Pseudofragment.dir/source/Pseudofragment.cpp.o] Error 1
make[1]: *** [CMakeFiles/Pseudofragment.dir/all] Error 2
make: *** [all] Error 2

It appears a particular header file for Boost isn't available? I'm not sure what to make of this.

**Comment by AlanKerstjens** [comment]
Hi @Tenchberry

I couldn't reproduce your issue on a fresh install of CentOS7. However, I believe you might have incompatible Boost and RDKit versions. It seems that [`<boost/detail/endian.hpp>` was deprecated with Boost 1.73](https://github.com/boostorg/endian/issues/45). From that version onward one should use `<boost/predef.h>` instead. The RDKit made that [switch in the `2019_03_1` release](https://github.com/rdkit/rdkit/commit/b3374150944ac4c3e0bba69e1285d02937829bc1#diff-425ecf8c60e47bec1952c556c93b42ca39585ccdcfb8ae6ec9c337137f081183). If you are using an older version of the RDKit with a more modern version of Boost you'll get said error, as it's trying to include a non-existing header file.

Could you check your Boost and RDKit versions to see if they are compatible? If you followed the instructions on the `README` I assume you created a new conda environment. I'm surprised this mismatch somehow happened. Perhaps CMake picked up a system-wide Boost installation. If you are using a system CMake install as opposed to the one of the conda environment this is to be expected. You can try adding `-DBOOST_INCLUDEDIR=${CONDA_PREFIX}/include -DBOOST_LIBRARYDIR=${CONDA_PREFIX}/lib -DBoost_NO_SYSTEM_PATHS=ON` to the CMake command. You can find some [more information on how CMake finds Boost here](https://cmake.org/cmake/help/latest/module/FindBoost.html).

**Comment by Tenchberry** [comment]
Hi again, apologies for the delay on this.

So upon a fresh retry and manually installing the newest version of RDKit on a conda environment, LEADD is now working fine. 

Thanks for your help with this.
